env:
  - distro: debianjessie
    init: "/sbin/init"
    run_opts: ""
    playbook: test.yml
  - distro: ubuntutrusty
    init: "/sbin/init"
    run_opts: ""
    playbook: test.yml
  - distro: ubuntuxenial
    init: "/sbin/init"
    run_opts: ""
    playbook: test.yml

services:
  - docker

before_install:
  - docker pull jebovic/${distro}-ansible:latest

script:
  # run container
  - container_id=$(mktemp)
  - docker run --detach --privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro -p 80:80 --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ${run_opts} jebovic/${distro}-ansible:latest "${init}" > "${container_id}"
  # syntax checking
  - docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/${playbook} --syntax-check
  # test role
  - docker exec "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/${playbook}
  # test role idempotence
  - idempotence=$(mktemp)
  - docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/${playbook} | tee -a ${idempotence}
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  # test role tasks
  - docker exec --tty "$(cat ${container_id})" env TERM=xterm systemctl --no-pager status mysql
  - docker exec --tty "$(cat ${container_id})" env TERM=xterm systemctl --no-pager stop mysql
  - docker exec --tty "$(cat ${container_id})" env TERM=xterm systemctl --no-pager start mysql
  - docker exec "$(cat ${container_id})" mysql -u root -e 'show databases;'
  - docker exec "$(cat ${container_id})" mysql -u root -h 127.0.0.1 -e 'show databases;'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: NNMzuAj4nlRZG9//nwblFDhb+f01/8MSFEDTRbtYKRFMbu6cm08heG8yWhShI7qu0wnw+n+0iOmN5wBsB3c3OzSfd2Ov9aBmYOt70NZoKYfoM+ismMXIh5WrRIa4BJEL3mA1bBU4f+x6y92i6j2+dLDplX3F3GhiYnMaW1CaYtM+vGoKw0eRPLD0b/OMz4vNXfR5eaCZRdm0ztZOrX6DpUzpI8F5lBdLGGspn+4lHO1Ke9tKJF8TNbYn/pdKba9ObUR8g5N8+MtLvbZR+gYkkAFlMhXGjnEj/JizTu0vG+rWjZLW/uTT5PrG09sGvYpG30yYeuMN4loAZ8qfJH7p8NpqUx/UsGSS2of+nN4wJk/bmVU1ax8c5ryNil5nPzaWQn34coGx7Yx2/1hhmtawRTTeJsDSDCm8FsFHifI58Q0hJFBNZmG9MoJtZSwXYGhwJgsB6U5dGx0bFU0KuwEijG6X8QI3J2Ftkb1HgxjqgyWkOTxhjLPB7NR8NHuskKQVoou+7hSgFv+wKGTHFV+DzNJl8YHOh5rKmJhGke6lOsPHqmEELWEnt2yupJQIDupfYcjjudKImIsIOFxq5NocDdS+aPoPmLLlByhRAMEzpAepVD5Sv3Z9unVUOLDi883OEJY5YbYPczsXX72EUaB0f1RH21V4jcgdYb9hnhUbXsY=
